#pragma once

namespace duck {

const int SHADER_LOCATION_POSITION = 0;
const int SHADER_LOCATION_NORMAL = 1;
const int SHADER_LOCATION_TEXTURE_COORDINATE = 2;
const int SHADER_LOCATION_VELOCITY = 3;
const int SHADER_LOCATION_AGE = 4;

const int SHADER_UNIFORM_LOCATION_MODEL = 10;
const int SHADER_UNIFORM_CAMERA_POSITION = 14;
const int SHADER_UNIFORM_TIME = 15;
const int SHADER_UNIFORM_LOCATION_VIEW = 11;
const int SHADER_UNIFORM_LOCATION_PROJECTION = 12;
const int SHADER_UNIFORM_LOCATION_LIGHT_POSITION = 13;

}
